# Generated by Django 5.0.3 on 2024-05-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_image_register_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='img',
            field=models.ImageField(upload_to='train_images/'),
        ),
    ]
