# Generated by Django 5.0.3 on 2024-06-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_register_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='register',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='register',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='register',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='register',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='register',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='register',
            name='branch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='img',
            field=models.ImageField(upload_to='registered_users/'),
        ),
        migrations.AlterField(
            model_name='register',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
