# Generated by Django 5.1.1 on 2024-11-01 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_recognition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recognition',
            new_name='KnownFace',
        ),
    ]
